sudo: required
services:
  - docker

before_install:
  - docker build -t tchelidze/docker-sample-react -f Dockerfile.dev .

script:
  - docker run tchelidze/docker-sample-react npm run test -- --watchAll=false